[project]
name = "provider-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff==0.9.10",
    "httpx==0.28.1",
    "beautifulsoup4==4.13.3",
    "pytest-playwright==0.7.0",
    "python-dotenv==1.0.1",
    "anyio==4.8.0",
    "certifi==2025.1.31",
    "charset-normalizer==3.4.1",
    "greenlet==3.1.1",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "idna==3.10",
    "iniconfig==2.0.0",
    "packaging==24.2",
    "playwright==1.50.0",
    "pluggy==1.5.0",
    "pyee==12.1.1",
    "pytest==8.3.5",
    "pytest-base-url==2.1.0",
    "python-slugify==8.0.4",
    "requests==2.32.3",
    "sniffio==1.3.1",
    "soupsieve==2.6",
    "text-unidecode==1.3",
    "typing-extensions==4.12.2",
    "urllib3==2.3.0",
    "provider-data",
]

[tool.uv]
package = true
