[project]
name = "provider-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.8.2",
    "httpx>=0.28.1",
    "beautifulsoup4>=4.12.3",
    "pytest-playwright>=0.6.2",
    "python-dotenv>=1.0.1",
]

[project.scripts]
hello = "provider_data:cloudflare_geojson"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

