name: update dev data

on:
  push:
    branches: [ "main" ]

jobs:
  environment:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - run: pip install -r requirements.txt

      - name: "prep env"
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: echo -n $DOTENV | base64 -d > .env

      - name: "update dev data"
        run: for i in src/provider_data/*.py; do echo $i; python $i --refresh; done
