name: update dev data

on:
  push:
    branches: [ "main" ]

jobs:
  environment:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Allow uv to use the system Python by default
        run: echo "UV_SYSTEM_PYTHON=true" >> $GITHUB_ENV

      - name: "install uv"
        uses: astral-sh/setup-uv@v5

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: "install dependencies"
        run: uv sync --all-extras --dev

      - name: "prep env"
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: echo -n $DOTENV | base64 -d > .env

      - name: "update dev data"
        run: for i in src/provider_data/*.py; do echo $i; uv run $i --refresh; done
