name: update main data

on:
  workflow_dispatch:

jobs:
  environment:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "prep env"
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: |
          echo -n $DOTENV | base64 -d > .env

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5

      - name: "Install the project"
        run: uv sync --all-extras --dev

      - name: "enable env"
        run: |
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: "update main data"
        run: |
          set +e
          failed_scripts=()
          for i in provider_data/*.py; do
            echo "updating $i..."
            uv run $i --prod
            if [ $? -ne 0 ]; then
              echo "WARNING: $i failed with exit code $?"
              failed_scripts+=("$i")
            fi
          done
          uv run provider_data/utils/generate_sitemap.py
          echo "------------------------------------"
          if [ ${#failed_scripts[@]} -gt 0 ]; then
            echo "WARNING: these updates failed:"
            for script in "${failed_scripts[@]}"; do
              echo "  - $script"
            done
            echo "continuing..."
          else
            echo "all updates completed successfully"
          fi
