name: update dev data

on:
  push:
    branches: [ "main" ]

jobs:
  environment:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5

      - name: "Install the project"
        run: uv sync --all-extras --dev

      - name: "prep env"
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: |
          echo -n $DOTENV | base64 -d > .env
          source .venv/bin/activate

      - name: "update dev data"
        run: for i in provider_data/*.py; do echo $i; $i --refresh; done
        working-directory: src
